### ISSUE TITLE
Some errors.

### ISSUE THREAD

**Issue by Alexkral** [tim-janik/zcam-js#1]
Thanks to this I have found some errors in my implementation, however I have also found some in yours:

- In Jzazbz_from_xyz and Izazbz_from_xyz, Y_D65 must be calculated before X_D65. For the inverse model your order is correct. You             can check it in the MATLAB code provided by the authors.

- The matrix for converting Izazbz to R'G'B' in the supplementary document for computing the inverse model is wrong. Should be:

     1 ,0, 0,
     3.524000, −4.066708, 0.542708,
     0.199076, 1.096799, −1.295875

because the luminance of R'G'B' comes from I, so the inverse matrix is:

     1, 0, 0,
     1, -0.277210086543079, -0.116094632312238,
     1, -0.234624285297858, -0.869939212212158

Without these two changes, there is a very noticeable shift of blues to purple/magenta.

EDIT: Sorry, the matrix is correct, I don't know what I was doing wrong.

**Comment by tim-janik** [comment]
> Thanks to this I have found some errors in my implementation, however I have also found some in yours:
> 
>     * In Jzazbz_from_xyz and Izazbz_from_xyz, Y_D65 must be calculated before X_D65. For the inverse model your order is correct. You             can check it in the MATLAB code provided by the authors.

I have not seen the MATLAB code by the authors. Do you have a link where it can be accessed?

Can you please elaborate what change exactly you are proposing?

**Comment by Alexkral** [comment]
Here's the link:

[https://opticapublishing.figshare.com/articles/software/JzAzBz_m/5016299](url)

But you are using different names for the variables, so everything is OK.

**Comment by tim-janik** [comment]
> Here's the link:
> 
> https://opticapublishing.figshare.com/articles/software/JzAzBz_m/5016299

Ah, I thought you were referring to Matlab code for ZCAM, but thanks anyway.

> But you are using different names for the variables, so everything is OK.

BTW, here's a post of mine detailing some of the issues I ran into during the implementation, particularly with the supplementary values:

https://testbit.eu/2022/zcam-in-javascript
